### DISCUSSION TITLE
workflowSchedule for Workflows with Parameters

### DISCUSSION THREAD

**Discussion by ismailhafid1** [microsoft/AL-Go#1680] [Q&A]
workflowSchedule is perfect for us to schedule workflows during the weekends n it s working fine with Update System Files, my only issue is scheduling workflows that have specific parameters for example : Publish To Environment and Create Release , both of these workflows have different specific parameters with different names and different type of values , is there a way to specify these parameters in my settings ? or those type of workflows arent supported yet ?

**Comment by freddydk** [comment]
Currently, you cannot really do this with settings alone.
What you can do is to create a new workflow, which runs on a schedule and spawns another workflow with the parameters you want.
An example of this could be:

```
name: 'PublishToProd'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 5"

env:
  appVersion: 'Current'
  environmentName: 'PROD'

jobs:
  Initialization:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Trigger Publish To Environment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          workflow_id: PublishToEnvironment.yaml
          ref: main
          inputs: '{"appVersion": ${{ env.appVersion }}, "environmentName": ${{ env.environmentName}} }'
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
```

We will probably find a better way to support this at a later time.
