### ISSUE TITLE
Schedule not executed

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL-Go#1004]
According to this [documentation](https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md)
I have added the following entries to `.github/AL-Go-settings.json`:
``` 
  "CurrentSchedule": "0 3 * * *",
  "NextMinorSchedule": "0 2 * * 6",
  "NextMajorSchedule": "0 2 * * 0"
```
However the pipelines are not running automatically.

My colleagues have currently solved this issue by adding a cron entry in `Current.yaml`
```
name: ' Test Current'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
```

Do I need to activate another setting?
