### ISSUE TITLE
[Question]: Is it possible to change what branch CICDSchedule runs on?

### ISSUE THREAD

**Issue by AlexanderMarcher** [microsoft/AL-Go#1470]
### Question

Hello

We are trying to use CICDSchedule to build and deploy from our "main" branch, but it seems to only run on the branch that is set as default. Is it possible to overwrite this?

**Comment by freddydk** [comment]
When defining a schedule on a GitHub workflow, it always runs on the default branch.
You can however create your own custom GitHub workflow, which basically just runs a different workflow and run that custom workflow on a schedule.
Example, this workflow will publish the latest release to a PROD environment every Friday evening:
```
name: 'PublishToProd'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 5"

env:
  appVersion: 'Current'
  environmentName: 'PROD'

jobs:
  Initialization:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Trigger Publish To Environment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          workflow_id: PublishToEnvironment.yaml
          ref: main
          inputs: '{"appVersion": ${{ env.appVersion }}, "environmentName": ${{ env.environmentName}} }'
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
```

This mechanism will work with all workflows, which can be executed using workflow_dispatch.
